import Pelicula from "../clases/Pelicula.js";
//lista de todas las peliculas de la pagina
const pelicula_1= new Pelicula(`pelicula_1`,`Dragon Ball Z: La batalla de los dioses`,`./assets/peliculas/Caraptula/Dragon_Ball_Z_La_batalla_de_los_dioses.jpg`, `Beerus, el dios de la destrucción, ha despertado después de años de letargo. Al escuchar que un súper saiyan logró derrotar a Freezer, viaja a la Tierra para retarlo. Goku deberá prepararse para el combate más difícil de su vida.`, `11 de Octubre del 2013`,`2013`, `Masahiro Hosoda`, `85 minutos`, `null`)
const pelicula_2= new Pelicula(`pelicula_2`,`Una voz Silenciosa`, `./assets/peliculas/Caraptula/Una_voz_Silenciosa.jpg`,`Shôko Nishimiya, una estudiante de primaria sorda, empieza a sentir el bullying de sus nuevos compañeros cuando se cambia de colegio. El peor de todos es Ishida Shôya, quien termina por forzar que Nishimiya se cambie de escuela. Años después, Ishida buscará la redención de sus malas acciones.`, `17 de Septiembre de 2016`, `2016`, `Naoko Yamada`, `129 minutos`, `null`)
const pelicula_3= new Pelicula(`pelicula_3`,`Your Name`, `./assets/peliculas/Caraptula/Your_Name.jpg`, `Mitsuha es una adolescente que detesta su vida rural en el campo. Por otro lado, Taki es un chico que vive en Tokio y sueña con ser un artista o un arquitecto. Los destinos de estos jóvenes se entrelazan la noche en que dos estrellas caen del cielo, y comienzan a intercambiar sus cuerpos de la noche a la mañana. Con el pasar del tiempo, desarrollan maneras de comunicarse entre ellos y un creciente anhelo de conocerse en persona.`, `26 de Agosto de 2016`,`2016`, `Makoto Shinkai`, `106 minutos`, `null`)
const pelicula_4= new Pelicula(`pelicula_4`,`Demon Slayer: El Tren Infinito`, `./assets/peliculas/Caraptula/Demon_Slayer_El_Tren_Infinito.jpg`, `Tanjiro y sus amigos unen fuerzas con un poderoso espadachín para combatir a los demonios que viajan en un tren en movimiento.`, `16 de Octubre de 2020`,`2020`, `Harou Sotozaki`, `117 minutos`, `null`)
const pelicula_5= new Pelicula(`pelicula_5`,`El Tiempo Contigo`, `./assets/peliculas/Caraptula/El_tiempo_contigo.jpg`, `El estudiante de secundaria Hodaka Morishima huye de su problemática casa rural a Tokio, donde se hace amigo de una niña huérfana que puede manipular el clima.`, `19 de Julio de 2019`,`2019`, `Makoto Shinkai`, `114 minutos`, `null`)
const pelicula_6= new Pelicula(`pelicula_6`,`Mazinger Z Infinity`, `./assets/peliculas/Caraptula/Mazinger_Z_Infinity.jpg`, `El planeta se encuentra en un momento de paz y prosperidad tecnológica. Sin embargo, el Doctor Infierno y sus secuaces vuelven a sembrar el caos y obligan a Koji Kabuto a volver a ponerse a los mandos del Mazinger Z.`, `13 de Enero de 2018`,`2018`, `Junji Shimizu`, `94 minutos`, `null`)
const pelicula_7= new Pelicula(`pelicula_7`,`El Niño y la Bestia`, `assets/peliculas/Caraptula/El_niño_y_la_bestia.jpg`, `Kyuta es un niño solitario que vive en Tokio. Kumatetsu es un ser sobrenatural aislada en un mundo imaginario. Un día Kyuta cruza la frontera al mundo imaginario y entabla amistad con la criatura.`, `11 de Julio de 2015`,`2015`, `Mamoru Hosoda.`, `120 minutos`, `null`)
const pelicula_8= new Pelicula(`pelicula_8`,`Amor de Gata`, `./assets/peliculas/Caraptula/Amor_de_gata.jpg`, `La línea entre humanos y animales comienza a desdibujarse cuando una chica peculiar se transforma en una gata para llamar la atención de su enamorado.`, `31 de Octubre de 2020`,`2020`, `Junichi sato y Tomotaka Shibayama`, `104 minutos`, `null`)
const pelicula_9= new Pelicula(`pelicula_9`,`Los Caballeros del Zodíaco: La leyenda del santuario`, `./assets/peliculas/Caraptula/caballeros_zodiaco_leyenda_santuario.jpg`, `Los guerreros llamados "Santos" son campeones de la esperanza que aparecen cuando el mal amenaza al mundo.`, `21 de Junio de 2014`,`2014`, `Keiichi Sato`, `93 minutos`, `null`)
const pelicula_10= new Pelicula(`pelicula_10`,`Digimon Adventure: Last Evolution Kizuna`, `./assets/peliculas/Caraptula/Digimon_Adventure_Last_Evolution_Kizuna.jpg`, `Tai y su digimon Agumon viven una última aventura juntos, en la que se dan cuenta de que, mientras más lucha un digimon, menos tiempo de relación queda.`, `21 de Febrero de 2020`,`2020`, `Tomohisa Taguchi y Kojin Ochi`, `95 minutos`, `null`)
const pelicula_11= new Pelicula(`pelicula_11`,`Pokémon Mewtwo contraataca: Evolución`, `./assets/peliculas/Caraptula/Pokémon_Mewto_contraataca_evolución.jpg`, `El Dr. Fuji crea un arma viva tras clonar al legendario Pokémon Mew, pero Mewtwo desarrolla su propio plan para destruir el mundo. Ash, Pikachu y sus amigos deben evitar la catástrofe.`, `12 de Julio de 2019`,`2019`, `Kenihiko Yuyama, Tetsuo Yajima y Motonori Sakakibara`, `98 minutos`, `null`)
const pelicula_12= new Pelicula(`pelicula_12`,`My Hero Academia: Two Heroes`, `./assets/peliculas/Caraptula/My_Hero_Academia_Two_Heroes.png`, `Deku y All-Might visitan la isla I, una ciudad flotante hecha por el hombre. Allí, conocen a una chica y pelean contra un villano que domina el lugar. Además, se develará información sobre el pasado de All-Might.`, `3 de Agosto de 2018`,`2018`, `Kenji Nagasaki`, `97 minutos`, `null`)
const pelicula_13= new Pelicula(`pelicula_13`,`Sailor Moon Eternal`, `./assets/peliculas/Caraptula/Sailor_Moon_Eternal.jpg`, `Cuando un poder oscuro envuelve la Tierra después de un eclipse solar total, los Sailor Guardians deben reunirse para devolver la luz al mundo.`, `8 de Enero de 2021`,`2021`, `Chiaki Kon`, `160 minutos`, `null`)
const pelicula_14= new Pelicula(`pelicula_14`,`Code Geass: Fukkatsu no Lelouch`, `./assets/peliculas/Caraptula/Code_Geass_Fukkatsu_no_Lelouch.jpg`, `Varios meses después de la muerte de Lelouch, Suzuki y Nunnally realizan una visita diplomática a un reino del desierto, donde se rencuentran con Knightmare Frame, quien los derrota y los secuestra.`, `9 de Febrero de 2019`,`2019`, `Goro Taniguchi`, `114 minutos`, `null`)
const pelicula_15= new Pelicula(`pelicula_15`,`Scream 5`, `./assets/peliculas/Caraptula/Scream_5.jpg`, `25 años después de que una racha de asesinatos brutales conmocionara a la tranquila ciudad de Woodsboro, un nuevo asesino imitador se ha puesto la máscara de Ghostface para resucitar secretos del pasado.`, `14 de Enero de 2022`,`2022`, `Matt bettinelli-Olpin y Tyler Gillett`, `114 minutos`, `null`)
const pelicula_16= new Pelicula(`pelicula_16`,`Annabelle 3: Vuelve a casa:`, `./assets/peliculas/Caraptula/Annabelle_3_vuelve_a_casa.jpg`, `Ed y Lorraine Warren tratan de encerrar bajo llave a Annabelle, una muñeca poseída. Como demonólogos la colocaran en una vitrina bendecida como medida de seguridad, sin embargo, una noche terrorífica Annabelle despertará a otros espíritus malignos que se encuentran en la habitación y que tendrán una nueva fijación: la hija pequeña del matrimonio y sus amigos.`, `20 de Junio de 2019`,`2019`, `Gary Daulberman`, `106 minutos`, `null`)
const pelicula_17= new Pelicula(`pelicula_17`,`El Conjuro 3`, `./assets/peliculas/Caraptula/El_conjuro_3.jpg`, `Los investigadores de fenómenos paranormales Ed y Lorraine Warren se enfrentan a un nuevo caso: el de un hombre acusado de un terrible asesinato, que asegura haber sido poseído por un demonio.`, `26 de Mayo de 2021`,`2021`, `Michael Chaves`, `112 minutos`, `null`)
const pelicula_18= new Pelicula(`pelicula_18`,`Halloween`, `./assets/peliculas/Caraptula/Halloween.jpg`, `Han pasado 40 años desde que Laurie Strode sobrevivió a un feroz ataque del asesino enloquecido Michael Myers en la noche de Halloween. Encerrado en una institución, Myers logra escapar cuando su traslado en autobús sale terriblemente mal. Laurie ahora enfrenta un enfrentamiento aterrador cuando el loco enmascarado regresa a Haddonfield, Ill.`, `19 de octubre de 2018`,`2018`, `David Gordon Green`, `105 minutos`, `null`)
const pelicula_19= new Pelicula(`pelicula_19`,`El Hoyo`, `./assets/peliculas/Caraptula/El_Hoyo.jpg`, `En el futuro, los prisioneros se alojan en celdas verticales, observando cómo los presos de las celdas superiores son alimentados mientras los de abajo mueren de hambre.`, `8 de Noviembre de 2019`,`2019`, `Galder Gaztelu-Urrutia`, `94 minutos`, `null`)
const pelicula_20= new Pelicula(`pelicula_20`,`La Monja`, `./assets/peliculas/Caraptula/La_monja.jpg`, `Una monja se suicida en una abadía rumana y el Vaticano envía a un sacerdote y una novicia a investigar lo sucedido. Lo que ambos encuentran allí es un secreto perverso que los enfrentará cara a cara con el mal en su esencia más pura.`, `7 de Septiembre de 2018`,`2018`, `Corin Hardy`, `96 minutos`, `null`)
const pelicula_21= new Pelicula(`pelicula_21`,`Alerta Roja`, `./assets/peliculas/Caraptula/Alerta_roja.jpg`, `John Hartley, agente de la Interpol, no tendrá otro remedio que aliarse con el ladrón de arte más célebre de todos los tiempos, Nolan Booth, para capturar a la ladrona de arte más buscada del presente: la seductora y peligrosa Sarah Black.`, `4 de Noviembre de 2021`,`2021`, `Rawson Marshall Thunber`, `118 minutos`, `null`)
const pelicula_22= new Pelicula(`pelicula_22`,`Un jefe en pañales 2: Negocios de familia`, `./assets/peliculas/Caraptula/Un_jefe_en_pañales_2_Negocios_de_familia.jpg`, `Theodore Templeton y su hermano, ahora adultos, toman una fórmula mágica que los transforma en bebés durante 48 horas. Juntos, deben evitar que un villano convierta a otros niños pequeños en monstruitos insoportables.`, `2 de Julio de 2021`,`2021`, `Tom McGrath`, `107 minutos`, `null`)
const pelicula_23= new Pelicula(`pelicula_23`,`Bad Boys 3`, `./assets/peliculas/Caraptula/Bad_Boys_3.jpg`, `Los policías de la vieja escuela Mike Lowery y Marcus Burnett vuelven a patrullar juntos para derrotar al líder vicioso de un cartel de drogas de Miami. El recién creado equipo de élite AMMO del departamento de policía de Miami junto con Mike y Marcus se enfrentan al despiadado Armando Armas.`, `17 de Enero de 2020`,`2020`, `Bilall Fallah y Adil El Arbi`, `124 minutos`, `null`)
const pelicula_24= new Pelicula(`pelicula_24`,`Wifi Ralph`, `./assets/peliculas/Caraptula/Wifi_Ralph.jpg`, `Para dar mayor emoción a la vida de su amiga Vanéllope, Ralph decide crear una nueva ruta en su juego Sugar Rush. Sin embargo, las consecuencias de esta decisión serán más preocupantes que divertidas: uno de los mandos del juego se rompe y el señor Litwak decide apagar la máquina para siempre.`, `21 de Noviembre de 2018`,`2018`, `Rich Moore y Phil Johnston`, `112 minutos`, `null`)
const pelicula_25= new Pelicula(`pelicula_25`,`Los Minions`, `./assets/peliculas/Caraptula/los_minions.jpg`, `Los minions, ingenuos y torpes ayudantes de villano, llevan buscando, desde el principio de los tiempos, un verdadero malhechor al que servir. A lo largo de una evolución de millones de años, los minions se han puesto al servicio de los amos más despreciables.`, `8 de Julio de 2015`,`2015`, `Pierre Coffin y Kyle Balda`, `91 minutos`, `null`)
const pelicula_26= new Pelicula(`pelicula_26`,`Venom 2: Carnage Liberado`, `./assets/peliculas/Caraptula/Venom_2_Carnage_Liberado.jpg`, `Después de encontrar un cuerpo anfitrión en el periodista de investigación Eddie Brock, el simbionte alienígena debe enfrentarse a un nuevo enemigo, Carnage, el alter ego del asesino en serie Cletus Kasady.`, `1 de Octubre de 2021`,`2021`, `Andy Serkis`, `97 minutos`, `null`)
const pelicula_27= new Pelicula(`pelicula_27`,`Los indestructibles 3`, `./assets/peliculas/Caraptula/Los_Indestructibles.jpg`, `Barney Ross, Lee Christmas y el resto de los Mercenarios deberán enfrentarse a Stonebanks, el otro fundador del grupo que ha vuelto. Los caminos de los dos amigos fundadores del grupo se separaron cuando Stonebanks se convirtió en traficante de armas.`, `15 de Agosto de 2014`,`2014`, `Patrick Hughes`, `126 minutos`, `null`)
const pelicula_28= new Pelicula(`pelicula_28`,`Avengers Era de Ultron`, `./assets/peliculas/Caraptula/Avengers_era_de_ultron.jpg`, `Tony Stark quiere lanzar un nuevo programa de paz, pero algo sale mal y acaba creando a Ultrón, un robot que quiere destruir a la humanidad. Thor, Hulk y el resto de los Vengadores deberán juntar sus fuerzas una vez más para luchar contra el robot.`, `1 de Mayo de 2015`,`2015`, `Joss Whedon`, `141 minutos`, `null`)
const pelicula_29= new Pelicula(`pelicula_29`,`Batman vs Superman: El origen de la justicia`, `./assets/peliculas/Caraptula/Batman_vs_Superman_amanecer_justicia.jpg`, `Mientras el mundo debate qué tipo de héroe necesita, las hazañas de Superman tienen peligrosas consecuencias. En plena guerra entre el vigilante de Gotham y el defensor de Metrópolis, una nueva amenaza pone a la humanidad en grave peligro.`, `25 de Marzo de 2016`,`2016`, `Zack Snyder`, `151 minutos`, `null`)
const pelicula_30= new Pelicula(`pelicula_30`,`300`, `./assets/peliculas/Caraptula/300.jpg`, `La trama describe la historia del Rey Espartano Leónidas y sus 300 guerreros espartanos que pelearon a muerte contra el "dios-rey" persa Jerjes I  y su ejército de más de 100.000 soldados.`, `9 de marzo de 2007`,`2007`, `Zack Snyder`, `117 minutos`, `null`)
const pelicula_31= new Pelicula(`pelicula_31`,`Matrix`, `./assets/peliculas/Caraptula/Matrix.jpg`, `El programador informático Thomas Anderson, más conocido en el mundo de los "hacker" como Neo, está en el punto de mira del temible agente Smith. Otros dos piratas informáticos, Trinity y Morfeo, se ponen en contacto con Neo para ayudarlo a escapar. Matrix te posee.`, `9 de Julio de 1999`,`1999`, `Lana Wachowski y Lilly Wachowski`, `148 minutos`, `null`)
const pelicula_32= new Pelicula(`pelicula_32`,`Rambo Acorralado Part II`, `./assets/peliculas/Caraptula/Rambo_Acorralado_Parte_II.jpg`, `El ex Boina Verde John Rambo,es liberado de la cárcel por el coronel Troutman para que le ayude en la búsqueda de prisioneros de guerra americanos en el sureste de Asia.`, `22 de Mayo de 1985`,`1985`, `George P. Cosmatos`, `96 minutos`, `null`)
const pelicula_33= new Pelicula(`pelicula_33`,`The Batman`, `./assets/peliculas/Caraptula/The_Batman.jpg`, `En su segundo año luchando contra el crimen, Batman explora la corrupción existente en la ciudad de Gotham y el vínculo de esta con su propia familia. Además, entrará en conflicto con un asesino en serie conocido como "el Acertijo".`, `4 de Marzo de 2022`,`2022`, `Matt Reeves`, `176 minutos`, `null`)
const pelicula_34= new Pelicula(`pelicula_34`,`Dune`, `./assets/peliculas/Caraptula/Dune.jpg`, `Arrakis, también denominado "Dune", se ha convertido en el planeta más importante del universo. A su alrededor comienza una gigantesca lucha por el poder que culmina en una guerra interestelar.`, `15 de Septiembre de 2021`,`2021`, `Denis Villeneuve`, `156 minutos`, `null`)
const pelicula_35= new Pelicula(`pelicula_35`,`Piratas del Caribe: La maldición del Perla Negra`, `./assets/peliculas/Caraptula/Piratas_del_Caribe_la_maldición_del_Perla_Negra.jpg`, `El capitán Barbossa le roba el barco al pirata Jack Sparrow y secuestra a Elizabeth, amiga de Will Turner. Barbossa y su tripulación son víctimas de un conjuro que los condena a vivir eternamente y a transformarse cada noche en esqueletos vivientes.`, `16 de Agosto de 2003`,`2003`, `Gore Verbinski`, `143 minutos`, `null`)
const pelicula_36= new Pelicula(`pelicula_36`,`Furia de Titanes 2`, `./assets/peliculas/Caraptula/Furia_De_Titanes_2.jpg`, `Perseo, hijo de Zeus y una mortal, se embarca en una peligrosa misión para salvar la vida de la princesa Andrómeda. Atrapado en una guerra entre dioses, en su épico viaje tendrá que enfrentarse a criaturas aterradoras y poderosas. Entretanto, Hades, dios del inframundo de los muertos planea derrocar a Zeus, el rey de los dioses del Olimpo.`, `1 de abril de 2010`,`2010`, `Louis Leterrier`, `99 minutos`, `null`)
const pelicula_37= new Pelicula(`pelicula_37`,`El Señor de los Anillos: El retorno del Rey`, `./assets/peliculas/Caraptula/El_Señor_de_los_Anillos_el_retorno_del_Rey.jpg`, `La batalla por la Tierra Media ha empezado. Las fuerzas de Saruman han sido destruidas y por primera vez parece que hay una pequeña esperanza. Sin embargo, el poder de Sauron crece y su interés se centra en Gondor, el último reducto de los hombres, cuyo heredero es Aragorn.`, `25 de Diciembre de 2003`,`2003`, `Peter Jackson`, `201 minutos`, `null`)
const pelicula_38= new Pelicula(`pelicula_38`,`¿Qué Paso Ayer?`, `./assets/peliculas/Caraptula/Que_paso_ayer.jpg`, `Dos días antes de su boda, Doug y tres amigos viajan a Las Vegas para una fiesta inolvidable y salvaje. De hecho, cuando los tres acompañantes despiertan la mañana siguiente, no recuerdan nada ni encuentran a Doug. Con poco tiempo por delante, los tres amigos intentan recordar sus pasos y encontrar a Doug para que regrese a Los Ángeles para su boda.`, `28 de Agosto de 2009`,`2009`, `Todd Phillips`, `100 minutos`, `null`)
const pelicula_39= new Pelicula(`pelicula_39`,`Scary Movie`, `./assets/peliculas/Caraptula/Scary_Movie.jpg`, `En esta parodia de las películas de terror modernas, un año después de atropellar a un hombre y deshacerse del cadáver, un grupo de adolescentes es acechado por un asesino en serie bastante inútil.`, `15 de Noviembre de 2000`,`2000`, `Keenen Ivory Wayans`, `88 minutos`, `null`)
const pelicula_40= new Pelicula(`pelicula_40`,`¡Shazam!`, `./assets/peliculas/Caraptula/Shazam!.jpg`, `El joven de 14 años Billy Batson puede convertirse en un superhéroe adulto solo con gritar la palabra "¡Shazam!". Pero dentro de un cuerpo superpoderoso, Shazam esconde un corazón de niño.`, `5 de Abril de 2019`,`2019`, `David F. Sandberg`, `132 minutos`, `null`)
const pelicula_41= new Pelicula(`pelicula_41`,`El Hombre de Acero`, `./assets/peliculas/Caraptula/El_hombre_de_acero.jpg`, `Con la inminente destrucción de Krypton, Jor-El y su mujer buscan una manera de preservar su raza y envían a su hijo a la Tierra para que viva entre los humanos. El bebé llega a una granja de Kansas, donde es criado en los valores de sus padres adoptivos, Martha y Jonathan Kent.`, `14 de Junio de 2013`,`2013`, `Zack Snyder`, `143 minutos`, `null`)
const pelicula_42= new Pelicula(`pelicula_42`,`La Matanza de Texas`, `./assets/peliculas/Caraptula/La_matanza_de_Texas.jpg`, `Un grupo de jóvenes se pierde en medio de las desérticas carreteras de Texas, y termina encontrándose con una familia de matarifes que los persigue con una sierra mecánica, descuartizándolos uno por uno.`, `1 de octubre de 1974`,`1974`, `Tobe Hooper`, `83 minutos`, `null`)
const pelicula_43= new Pelicula(`pelicula_43`,`Batman: El caballero de la noche asciende`, `./assets/peliculas/Caraptula/Batman_el_caballero_de_la_noche_asciende.JPG`, `Hace ya ocho años desde que Batman se convirtió en fugitivo al asumir la muerte de Harvey. La dura Ley Dent sigue aplacando la criminalidad de Gotham, aunque la llegada de una gata ladrona y un misterioso terrorista enmascarado lo cambiará todo.`, `27 de Julio de 2012`,`2012`, `Christopher Nolan`, `164 minutos`, `null`)
const pelicula_44= new Pelicula(`pelicula_44`,`La Liga de la Justicia de Zack Snyder`, `./assets/peliculas/Caraptula/La_Liga_de_la_Justicia_de_Zack_Snyder.JPG`, `Bruce Wayne se une a Diana Prince, tras el sacrificio de Superman, para reclutar a un equipo de metahumanos que protejan el mundo de una amenaza inminente de proporciones catastróficas.`, `18 de Marzo de 2021`,`2021`, `Zack Snyder`, `242 minutos`, `null`)
const pelicula_45= new Pelicula(`pelicula_45`,`Wonder Woman 1984`, `./assets/peliculas/Caraptula/Wonder_woman_1984.jpg`, `Diana Prince, conocida como Wonder Woman se enfrenta a Cheetah, una villana que posee fuerza y agilidad sobrehumanas.`, `25 de Diciembre de 2020`,`2020`, `Patty Jenkins`, `151 minutos`, `null`)
const pelicula_46= new Pelicula(`pelicula_46`,`Venom`, `./assets/peliculas/Caraptula/Venom.jpg`, `El periodista Eddie Brock intenta desenmascarar al genio científico Carlton Drake, el célebre fundador de la Fundación Vida.`, `5 de Octubre de 2018`,`2018`, `Ruben Fleischer`, `112 minutos`, `null`)
const pelicula_47= new Pelicula(`pelicula_47`,`Pantera Negra`, `./assets/peliculas/Caraptula/Pantera_Negra.jpg`, `En Black Panther, T'Challa es coronado rey de Wakanda luego de la muerte de su padre, pero su soberanía es cuestionada por un adversario que planea abandonar las políticas aislacionistas del país e iniciar una revolución mundial.`, `16 de Febrero de 2018`,`2018`, `Ryan Coogler`, `134 minutos`, `null`)
const pelicula_48= new Pelicula(`pelicula_48`,`Los Vengadores: Endgame`, `./assets/peliculas/Caraptula/Avengers_Endgame.jpeg`, `Después de los eventos devastadores de "Avengers: Infinity War", el universo está en ruinas debido a las acciones de Thanos, el Titán Loco. Con la ayuda de los aliados que quedaron, los Vengadores deberán reunirse una vez más para intentar detenerlo y restaurar el orden en el universo de una vez por todas.`, `26 de Abril de 2019`,`2019`, `Anthony Russo, Joe Russo`, `181 minutos`, `null`)
const pelicula_49= new Pelicula(`pelicula_49`,`Iron Man 3`, `./assets/peliculas/Caraptula/Iron_Man_3.jpg`, `El descarado y brillante Tony Stark, tras ver destruido todo su universo personal, debe encontrar y enfrentarse a un enemigo cuyo poder no conoce límites. Este viaje pondrá a prueba su entereza una y otra vez, y le obligará a confiar en su ingenio.`, `26 de Abril de 2013`,`2013`, `Shane Black`, `131 minutos`, `null`)
const pelicula_50= new Pelicula(`pelicula_50`,`Thor: Ragnarok`, `./assets/peliculas/Caraptula/Thor_Ragnarok.jpg`, `Thor está preso en el otro extremo del universo. Necesita regresar a tiempo para evitar que la todopoderosa Hela destruya su mundo, pero para escapar de su confinamiento y evitar el apocalipsis tendrá que vencer antes al increíble Hulk en un torneo de gladiadores.`, `3 de Noviembre de 2017`,`2017`, `Taika Waititi`, `130 minutos`, `null`)
const pelicula_51= new Pelicula(`pelicula_51`,`CODA`, `./assets/peliculas/Caraptula/CODA.jpg`, `Ruby es el único miembro con audición de una familia de sordos. Cada mañana, antes de ir a clases, trabaja con sus padres y su hermano tratando de mantener a flote su negocio. En el coro del instituto, Ruby descubre su pasión por la música.`, `13 de Agosto de 2021`,`2021`, `Sian Heder`, `111 minutos`, `null`)
const pelicula_52= new Pelicula(`pelicula_52`,`Focus: Maestros de la Estafa`, `./assets/peliculas/Caraptula/Focus.jpg`, `Nicky, un consumado maestro de la estafa, comienza un romance con Jess, una novata en el gremio. Mientras Nicky le enseña los trucos del oficio, Jess intenta estrechar lazos con él, pero este acercamiento hace que Nicky rompa de repente la relación.`, `27 de Febrero de 2015`,`2015`, `Glenn Ficarra y John Requa`, `104 minutos`, `null`)
const pelicula_53= new Pelicula(`pelicula_53`,`Sr. y Sra. Smith`, `./assets/peliculas/Caraptula/Sr._y_Sra._Smith.jpg`, `Tras cinco años de idilio conyugal, el matrimonio de John y Jane smith ha entrado en la rutina. Hasta que ambos descubren la verdad: ambos son fríos, letales y carísimos asesinos a sueldo de organizaciones enfrentadas.`, `9 de Junio de 2005`,`2005`, `Doug Liman`, `120 minutos`, `null`)
const pelicula_54= new Pelicula(`pelicula_54`,`Pasajeros`, `./assets/peliculas/Caraptula/Pasajeros.jpg`, `Dos pasajeros que viajan en hibernación a un planeta lejano despiertan, por un error técnico, 90 años antes de llegar a destino. Solos y rodeados de lujos, entre ellos surge el amor; sin embargo, descubren que hay una avería en la nave y tendrán que repararla a tiempo para salvar a las 5 000 personas que permanecen hibernando, y a sí mismos.`, `14 de Diciembre de 2016`,`2016`, `Morten Tyldum`, `105 minutos`, `null`)
const pelicula_55= new Pelicula(`pelicula_55`,`Los Agentes del Destino`, `./assets/peliculas/Caraptula/Los_agentes_del_destino.jpg`, `Justo cuando está a punto de ganar un lugar en el senado, el político David Norris conoce a una bailarina llamada Elise Sellas. A pesar de que David está herido, hombres misteriosos conspiran para mantenerlo lejos de la hermosa bailarina. David descubre que está frente a los agentes de Fate y, pensando en su futuro, tendrá que aceptar un camino sin Elise, o desafiar a Fate para estar con ella.`, `4 de Marzo de 2011`,`2011`, `George Nolfi`, `107 minutos`, `null`)
const pelicula_56= new Pelicula(`pelicula_56`,`Alien: El Octavo Pasajero`, `./assets/peliculas/Caraptula/Alien_El_octavo_pasajero.jpg`, `Tras acudir a una llamada de ayuda, la tripulación (Tom Skerritt, Sigourney Weaver, John Hurt) encuentra una voraz y horrible criatura abordo de una nave espacial.`, `28 de Marzo de 1980`,`1980`, `Ridley Scott`, `116 minutos`, `null`)
const pelicula_57= new Pelicula(`pelicula_57`, `Morbius`, `./assets/peliculas/Caraptula/Morbius.jpg`, `Ambientada en el universo de Spider Man, se centra en uno de sus villanos más icónicos, Morbius, un doctor que tras sufrir una enfermedad en la sangre y fallar al intentar curarse, se convirtió en un vampiro.`, `1 de abril de 2022`, `2022`, `Daniel Espinosa`, `104 minutos`, `null`)
const pelicula_58= new Pelicula(`pelicula_58`, `Doctor Strange en el Multiverso de la Locura`, `./assets/peliculas/Caraptula/Doctor_Strange_2.jpg`, `El Dr. Stephen Strange abre un portal al multiverso al utilizar un hechizo prohibido. Ahora, su equipo debe enfrentarse a una amenaza que podría destruirlo todo.`, `6 de mayo de 2022`, `2022`, `Sam Raimi`, `126 minutos`, `null`)
const pelicula_59= new Pelicula(`pelicula_59`, `El Proyecto Adam`, `./assets/peliculas/Caraptula/El_proyecto_Adam.jpg`, `Adam Reed, un viajero del tiempo y piloto de combate, aterriza en el año 2022. Allí, se encuentra con su yo de doce años y, junto a él, tratará de salvar el futuro.`, ` 28 de febrero de 2022`, `2022`, `Shawn Levy`, `106 minutos`, `null`)
const pelicula_60= new Pelicula(`pelicula_60`, `Jurassic World: Dominion`, `./assets/peliculas/Caraptula/Jurassic_World_Dominion.jpg`, `La isla Nublar y su parque han sido destruidos, pero el problema no se terminó. Con los dinosaurios dispersos por todo el mundo, la convivencia entre el presente y el pasado alcanza un nuevo nivel de tensión.`, `10 de junio de 2022`, `2022`, `Colin Trevorrow`, `147 minutos`, `null`)
//objeto a partir del cual se consultara todas las peliculas previamente instanciadas
export const lista_peliculas={
    Peliculas: [[pelicula_1, pelicula_2, pelicula_3, pelicula_4, pelicula_5, pelicula_6, pelicula_7, pelicula_8, pelicula_9, pelicula_10, pelicula_11, pelicula_12, pelicula_13, pelicula_14, pelicula_15, pelicula_16], [pelicula_17, pelicula_18, pelicula_19, pelicula_20, pelicula_21, pelicula_22, pelicula_23, pelicula_24, pelicula_25, pelicula_26, pelicula_27, pelicula_28, pelicula_29, pelicula_30, pelicula_31, pelicula_32], [pelicula_33, pelicula_34, pelicula_35, pelicula_36, pelicula_37, pelicula_38, pelicula_39, pelicula_40, pelicula_41, pelicula_42, pelicula_43, pelicula_44, pelicula_45, pelicula_46, pelicula_47, pelicula_48], [pelicula_49, pelicula_50, pelicula_51, pelicula_52, pelicula_53, pelicula_54, pelicula_55, pelicula_56,pelicula_58,pelicula_59,pelicula_60,pelicula_57]],
    Generos: {
        Anime: [[pelicula_1, pelicula_2, pelicula_3, pelicula_4, pelicula_5, pelicula_6, pelicula_7, pelicula_8, pelicula_9, pelicula_10, pelicula_11, pelicula_12, pelicula_13, pelicula_14]],
        Acción: [[pelicula_1, pelicula_4, pelicula_6, pelicula_7, pelicula_9, pelicula_10, pelicula_11, pelicula_12, pelicula_14, pelicula_18, pelicula_21, pelicula_23, pelicula_24, pelicula_25, pelicula_26, pelicula_27], [pelicula_28, pelicula_29, pelicula_30, pelicula_31, pelicula_32, pelicula_33, pelicula_34, pelicula_35, pelicula_36, pelicula_37, pelicula_40, pelicula_41, pelicula_44,pelicula_43, pelicula_45, pelicula_46], [pelicula_47, pelicula_48, pelicula_49, pelicula_50, pelicula_53,pelicula_57,pelicula_58,pelicula_60]],
        Romance: [[pelicula_2, pelicula_3, pelicula_5, pelicula_8, pelicula_51, pelicula_52, pelicula_53, pelicula_54, pelicula_55]],
        Aventura: [[pelicula_1, pelicula_6, pelicula_7, pelicula_10, pelicula_11, pelicula_14, pelicula_21, pelicula_22, pelicula_23, pelicula_24, pelicula_25, pelicula_26, pelicula_27, pelicula_28, pelicula_29, pelicula_30], [pelicula_31, pelicula_32, pelicula_33, pelicula_34, pelicula_35, pelicula_36, pelicula_37, pelicula_38, pelicula_40, pelicula_41, pelicula_44, pelicula_46, pelicula_47, pelicula_48, pelicula_49, pelicula_50], [pelicula_53,pelicula_54, pelicula_56,pelicula_57,pelicula_59,pelicula_60]],
        Marvel: [[pelicula_26, pelicula_28, pelicula_46, pelicula_47, pelicula_48, pelicula_49,pelicula_50,pelicula_57,pelicula_58]],
        DC: [[pelicula_29, pelicula_33, pelicula_40, pelicula_41, pelicula_43, pelicula_44, pelicula_45]],
        Terror: [[pelicula_15, pelicula_16, pelicula_17, pelicula_18, pelicula_19, pelicula_20, pelicula_39, pelicula_42, pelicula_56,pelicula_58]],
        Comedia: [[pelicula_1, pelicula_12, pelicula_21, pelicula_22, pelicula_23, pelicula_24, pelicula_25, pelicula_35, pelicula_38, pelicula_39, pelicula_40, pelicula_51, pelicula_52, pelicula_53]],
        Drama:[[pelicula_2, pelicula_3, pelicula_5, pelicula_14, pelicula_30, pelicula_33, pelicula_34, pelicula_37, pelicula_43, pelicula_45, pelicula_52, pelicula_54, pelicula_55]],
        Ciencia_Fision:[[pelicula_6, pelicula_12, pelicula_19, pelicula_26, pelicula_28, pelicula_29, pelicula_31, pelicula_34, pelicula_40, pelicula_41, pelicula_44, pelicula_46, pelicula_47, pelicula_48, pelicula_49, pelicula_50], [pelicula_54, pelicula_55, pelicula_56,pelicula_57,pelicula_58,pelicula_59,pelicula_60]],
        Fantasia:[[pelicula_1, pelicula_3, pelicula_4, pelicula_5, pelicula_7, pelicula_8, pelicula_9, pelicula_10, pelicula_11, pelicula_12, pelicula_13, pelicula_22, pelicula_24,pelicula_25, pelicula_31, pelicula_34], [pelicula_35, pelicula_36, pelicula_37, pelicula_41, pelicula_44, pelicula_46, pelicula_47, pelicula_48, pelicula_50]]
    },
    Estrenos:[pelicula_58,pelicula_59,pelicula_60,pelicula_33,pelicula_57],
    Vistas:[pelicula_1,pelicula_58,pelicula_44, pelicula_45, pelicula_60  ]
}
