import Pelicula from "../clases/Pelicula.js";
//lista de todas las peliculas de la pagina
const pelicula_1= new Pelicula(`pelicula_1`,`Dragon Ball Z: La batalla de los dioses`,`./assets/peliculas/Caraptula/Dragon_Ball_Z_La_batalla_de_los_dioses.jpg`, `Beerus, el dios de la destrucción, ha despertado después de años de letargo. Al escuchar que un súper saiyan logró derrotar a Freezer, viaja a la Tierra para retarlo. Goku deberá prepararse para el combate más difícil de su vida.`, `11 de Octubre del 2013`,`2013`, `Masahiro Hosoda`, `85 minutos`, `./assets/peliculas/Video/Dragon_Ball_Z_La_batalla_de_los_dioses.mp4`)
const pelicula_2= new Pelicula(`pelicula_2`,`Your Name`, `./assets/peliculas/Caraptula/Your_Name.jpg`, `Mitsuha es una adolescente que detesta su vida rural en el campo. Por otro lado, Taki es un chico que vive en Tokio y sueña con ser un artista o un arquitecto. Los destinos de estos jóvenes se entrelazan la noche en que dos estrellas caen del cielo, y comienzan a intercambiar sus cuerpos de la noche a la mañana. Con el pasar del tiempo, desarrollan maneras de comunicarse entre ellos y un creciente anhelo de conocerse en persona.`, `26 de Agosto de 2016`,`2016`, `Makoto Shinkai`, `106 minutos`, `./assets/peliculas/Video/Your_Name.mp4`)
const pelicula_3= new Pelicula(`pelicula_3`,`Demon Slayer: El Tren Infinito`, `./assets/peliculas/Caraptula/Demon_Slayer_El_Tren_Infinito.jpg`, `Tanjiro y sus amigos unen fuerzas con un poderoso espadachín para combatir a los demonios que viajan en un tren en movimiento.`, `16 de Octubre de 2020`,`2020`, `Harou Sotozaki`, `117 minutos`, `./assets/peliculas/Video/Demon_Slayer_El_Tren_Infinito.mp4`)
const pelicula_4= new Pelicula(`pelicula_4`,`El Tiempo Contigo`, `./assets/peliculas/Caraptula/El_tiempo_contigo.jpg`, `El estudiante de secundaria Hodaka Morishima huye de su problemática casa rural a Tokio, donde se hace amigo de una niña huérfana que puede manipular el clima.`, `19 de Julio de 2019`,`2019`, `Makoto Shinkai`, `114 minutos`, `./assets/peliculas/Video/El_tiempo_contigo.mp4`)
const pelicula_5= new Pelicula(`pelicula_5`,`Mazinger Z Infinity`, `./assets/peliculas/Caraptula/Mazinger_Z_Infinity.jpg`, `El planeta se encuentra en un momento de paz y prosperidad tecnológica. Sin embargo, el Doctor Infierno y sus secuaces vuelven a sembrar el caos y obligan a Koji Kabuto a volver a ponerse a los mandos del Mazinger Z.`, `13 de Enero de 2018`,`2018`, `Junji Shimizu`, `94 minutos`, `./assets/peliculas/Video/Mazinger_Z_Infinity.mp4`)
const pelicula_6= new Pelicula(`pelicula_6`,`Amor de Gata`, `./assets/peliculas/Caraptula/Amor_de_gata.jpg`, `La línea entre humanos y animales comienza a desdibujarse cuando una chica peculiar se transforma en una gata para llamar la atención de su enamorado.`, `31 de Octubre de 2020`,`2020`, `Junichi sato y Tomotaka Shibayama`, `104 minutos`, `./assets/peliculas/Video/Amor_de_gata.mp4`)
const pelicula_7= new Pelicula(`pelicula_7`,`Digimon Adventure: Last Evolution Kizuna`, `./assets/peliculas/Caraptula/Digimon_Adventure_Last_Evolution_Kizuna.jpg`, `Tai y su digimon Agumon viven una última aventura juntos, en la que se dan cuenta de que, mientras más lucha un digimon, menos tiempo de relación queda.`, `21 de Febrero de 2020`,`2020`, `Tomohisa Taguchi y Kojin Ochi`, `95 minutos`, `./assets/peliculas/Video/Digimon_Adventure_Last_Evolution_Kizuna.mp4`)
const pelicula_8= new Pelicula(`pelicula_8`,`My Hero Academia: Two Heroes`, `./assets/peliculas/Caraptula/My_Hero_Academia_Two_Heroes.png`, `Deku y All-Might visitan la isla I, una ciudad flotante hecha por el hombre. Allí, conocen a una chica y pelean contra un villano que domina el lugar. Además, se develará información sobre el pasado de All-Might.`, `3 de Agosto de 2018`,`2018`, `Kenji Nagasaki`, `97 minutos`, `./assets/peliculas/Video/My_Hero_Academia_Two_Heroes.mp4`)
const pelicula_9= new Pelicula(`pelicula_9`,`Annabelle 3: Vuelve a casa:`, `./assets/peliculas/Caraptula/Annabelle_3_vuelve_a_casa.jpg`, `Ed y Lorraine Warren tratan de encerrar bajo llave a Annabelle, una muñeca poseída. Como demonólogos la colocaran en una vitrina bendecida como medida de seguridad, sin embargo, una noche terrorífica Annabelle despertará a otros espíritus malignos que se encuentran en la habitación y que tendrán una nueva fijación: la hija pequeña del matrimonio y sus amigos.`, `20 de Junio de 2019`,`2019`, `Gary Daulberman`, `106 minutos`, `./assets/peliculas/Video/Annabelle_3_vuelve_a_casa.mp4`)
const pelicula_10= new Pelicula(`pelicula_10`,`El Conjuro 3`, `./assets/peliculas/Caraptula/El_conjuro_3.jpg`, `Los investigadores de fenómenos paranormales Ed y Lorraine Warren se enfrentan a un nuevo caso: el de un hombre acusado de un terrible asesinato, que asegura haber sido poseído por un demonio.`, `26 de Mayo de 2021`,`2021`, `Michael Chaves`, `112 minutos`, `./assets/peliculas/Video/El_conjuro_3.mp4`)
const pelicula_11= new Pelicula(`pelicula_11`,`Halloween`, `./assets/peliculas/Caraptula/Halloween.jpg`, `Han pasado 40 años desde que Laurie Strode sobrevivió a un feroz ataque del asesino enloquecido Michael Myers en la noche de Halloween. Encerrado en una institución, Myers logra escapar cuando su traslado en autobús sale terriblemente mal. Laurie ahora enfrenta un enfrentamiento aterrador cuando el loco enmascarado regresa a Haddonfield, Ill.`, `19 de octubre de 2018`,`2018`, `David Gordon Green`, `105 minutos`, `./assets/peliculas/Video/Halloween.mp4`)
const pelicula_12= new Pelicula(`pelicula_12`,`La Monja`, `./assets/peliculas/Caraptula/La_monja.jpg`, `Una monja se suicida en una abadía rumana y el Vaticano envía a un sacerdote y una novicia a investigar lo sucedido. Lo que ambos encuentran allí es un secreto perverso que los enfrentará cara a cara con el mal en su esencia más pura.`, `7 de Septiembre de 2018`,`2018`, `Corin Hardy`, `96 minutos`, `./assets/peliculas/Video/La_monja.mp4`)
const pelicula_13= new Pelicula(`pelicula_13`,`Alerta Roja`, `./assets/peliculas/Caraptula/Alerta_roja.jpg`, `John Hartley, agente de la Interpol, no tendrá otro remedio que aliarse con el ladrón de arte más célebre de todos los tiempos, Nolan Booth, para capturar a la ladrona de arte más buscada del presente: la seductora y peligrosa Sarah Black.`, `4 de Noviembre de 2021`,`2021`, `Rawson Marshall Thunber`, `118 minutos`, `./assets/peliculas/Video/Alerta_roja.mp4`)
const pelicula_14= new Pelicula(`pelicula_14`,`Bad Boys 3`, `./assets/peliculas/Caraptula/Bad_Boys_3.jpg`, `Los policías de la vieja escuela Mike Lowery y Marcus Burnett vuelven a patrullar juntos para derrotar al líder vicioso de un cartel de drogas de Miami. El recién creado equipo de élite AMMO del departamento de policía de Miami junto con Mike y Marcus se enfrentan al despiadado Armando Armas.`, `17 de Enero de 2020`,`2020`, `Bilall Fallah y Adil El Arbi`, `124 minutos`, `./assets/peliculas/Video/Bad_Boys_3.mp4`)
const pelicula_15= new Pelicula(`pelicula_15`,`Wifi Ralph`, `./assets/peliculas/Caraptula/Wifi_Ralph.jpg`, `Para dar mayor emoción a la vida de su amiga Vanéllope, Ralph decide crear una nueva ruta en su juego Sugar Rush. Sin embargo, las consecuencias de esta decisión serán más preocupantes que divertidas: uno de los mandos del juego se rompe y el señor Litwak decide apagar la máquina para siempre.`, `21 de Noviembre de 2018`,`2018`, `Rich Moore y Phil Johnston`, `112 minutos`, `./assets/peliculas/Video/Wifi_Ralph.mp4`)
const pelicula_16= new Pelicula(`pelicula_16`,`Venom 2: Carnage Liberado`, `./assets/peliculas/Caraptula/Venom_2_Carnage_Liberado.jpg`, `Después de encontrar un cuerpo anfitrión en el periodista de investigación Eddie Brock, el simbionte alienígena debe enfrentarse a un nuevo enemigo, Carnage, el alter ego del asesino en serie Cletus Kasady.`, `1 de Octubre de 2021`,`2021`, `Andy Serkis`, `97 minutos`, `./assets/peliculas/Video/Venom_2_Carnage_Liberado.mp4`)
const pelicula_17= new Pelicula(`pelicula_17`,`Batman vs Superman: El origen de la justicia`, `./assets/peliculas/Caraptula/Batman_vs_Superman_amanecer_justicia.jpg`, `Mientras el mundo debate qué tipo de héroe necesita, las hazañas de Superman tienen peligrosas consecuencias. En plena guerra entre el vigilante de Gotham y el defensor de Metrópolis, una nueva amenaza pone a la humanidad en grave peligro.`, `25 de Marzo de 2016`,`2016`, `Zack Snyder`, `151 minutos`, `./assets/peliculas/Video/Batman_vs_Superman_amanecer_justicia.mp4`)
const pelicula_18= new Pelicula(`pelicula_18`,`The Batman`, `./assets/peliculas/Caraptula/The_Batman.jpg`, `En su segundo año luchando contra el crimen, Batman explora la corrupción existente en la ciudad de Gotham y el vínculo de esta con su propia familia. Además, entrará en conflicto con un asesino en serie conocido como "el Acertijo".`, `4 de Marzo de 2022`,`2022`, `Matt Reeves`, `176 minutos`, `./assets/peliculas/Video/The_Batman.mp4`)
const pelicula_19= new Pelicula(`pelicula_19`,`Dune`, `./assets/peliculas/Caraptula/Dune.jpg`, `Arrakis, también denominado "Dune", se ha convertido en el planeta más importante del universo. A su alrededor comienza una gigantesca lucha por el poder que culmina en una guerra interestelar.`, `15 de Septiembre de 2021`,`2021`, `Denis Villeneuve`, `156 minutos`, `./assets/peliculas/Video/Dune.mp4`)
const pelicula_20= new Pelicula(`pelicula_20`,`El Señor de los Anillos: El retorno del Rey`, `./assets/peliculas/Caraptula/El_Señor_de_los_Anillos_el_retorno_del_Rey.jpg`, `La batalla por la Tierra Media ha empezado. Las fuerzas de Saruman han sido destruidas y por primera vez parece que hay una pequeña esperanza. Sin embargo, el poder de Sauron crece y su interés se centra en Gondor, el último reducto de los hombres, cuyo heredero es Aragorn.`, `25 de Diciembre de 2003`,`2003`, `Peter Jackson`, `201 minutos`, `./assets/peliculas/Video/El_Señor_de_los_Anillos_el_retorno_del_Rey.mp4`)
const pelicula_21= new Pelicula(`pelicula_21`,`¡Shazam!`, `./assets/peliculas/Caraptula/Shazam!.jpg`, `El joven de 14 años Billy Batson puede convertirse en un superhéroe adulto solo con gritar la palabra "¡Shazam!". Pero dentro de un cuerpo superpoderoso, Shazam esconde un corazón de niño.`, `5 de Abril de 2019`,`2019`, `David F. Sandberg`, `132 minutos`, `./assets/peliculas/Video/Shazam!.mp4`)
const pelicula_22= new Pelicula(`pelicula_22`,`El Hombre de Acero`, `./assets/peliculas/Caraptula/El_hombre_de_acero.jpg`, `Con la inminente destrucción de Krypton, Jor-El y su mujer buscan una manera de preservar su raza y envían a su hijo a la Tierra para que viva entre los humanos. El bebé llega a una granja de Kansas, donde es criado en los valores de sus padres adoptivos, Martha y Jonathan Kent.`, `14 de Junio de 2013`,`2013`, `Zack Snyder`, `143 minutos`, `./assets/peliculas/Video/El_hombre_de_acero.mp4`)
const pelicula_23= new Pelicula(`pelicula_23`,`La Liga de la Justicia de Zack Snyder`, `./assets/peliculas/Caraptula/La_Liga_de_la_Justicia_de_Zack_Snyder.JPG`, `Bruce Wayne se une a Diana Prince, tras el sacrificio de Superman, para reclutar a un equipo de metahumanos que protejan el mundo de una amenaza inminente de proporciones catastróficas.`, `18 de Marzo de 2021`,`2021`, `Zack Snyder`, `242 minutos`, `./assets/peliculas/Video/La_Liga_de_la_Justicia_de_Zack_Snyder.mp4`)
const pelicula_24= new Pelicula(`pelicula_24`,`Wonder Woman 1984`, `./assets/peliculas/Caraptula/Wonder_woman_1984.jpg`, `Diana Prince, conocida como Wonder Woman se enfrenta a Cheetah, una villana que posee fuerza y agilidad sobrehumanas.`, `25 de Diciembre de 2020`,`2020`, `Patty Jenkins`, `151 minutos`, `./assets/peliculas/Video/Wonder_woman_1984.mp4`)
const pelicula_25= new Pelicula(`pelicula_25`,`Pantera Negra`, `./assets/peliculas/Caraptula/Pantera_Negra.jpg`, `En Black Panther, T'Challa es coronado rey de Wakanda luego de la muerte de su padre, pero su soberanía es cuestionada por un adversario que planea abandonar las políticas aislacionistas del país e iniciar una revolución mundial.`, `16 de Febrero de 2018`,`2018`, `Ryan Coogler`, `134 minutos`, `./assets/peliculas/Video/Pantera_Negra.mp4`)
const pelicula_26= new Pelicula(`pelicula_26`,`Los Vengadores: Endgame`, `./assets/peliculas/Caraptula/Avengers_Endgame.jpeg`, `Después de los eventos devastadores de "Avengers: Infinity War", el universo está en ruinas debido a las acciones de Thanos, el Titán Loco. Con la ayuda de los aliados que quedaron, los Vengadores deberán reunirse una vez más para intentar detenerlo y restaurar el orden en el universo de una vez por todas.`, `26 de Abril de 2019`,`2019`, `Anthony Russo, Joe Russo`, `181 minutos`, `./assets/peliculas/Video/Avengers_Endgame.mp4`)
const pelicula_27= new Pelicula(`pelicula_27`,`Focus: Maestros de la Estafa`, `./assets/peliculas/Caraptula/Focus.jpg`, `Nicky, un consumado maestro de la estafa, comienza un romance con Jess, una novata en el gremio. Mientras Nicky le enseña los trucos del oficio, Jess intenta estrechar lazos con él, pero este acercamiento hace que Nicky rompa de repente la relación.`, `27 de Febrero de 2015`,`2015`, `Glenn Ficarra y John Requa`, `104 minutos`, `./assets/peliculas/Video/Focus.mp4`)
const pelicula_28= new Pelicula(`pelicula_28`,`Pasajeros`, `./assets/peliculas/Caraptula/Pasajeros.jpg`, `Dos pasajeros que viajan en hibernación a un planeta lejano despiertan, por un error técnico, 90 años antes de llegar a destino. Solos y rodeados de lujos, entre ellos surge el amor; sin embargo, descubren que hay una avería en la nave y tendrán que repararla a tiempo para salvar a las 5 000 personas que permanecen hibernando, y a sí mismos.`, `14 de Diciembre de 2016`,`2016`, `Morten Tyldum`, `105 minutos`, `./assets/peliculas/Video/Pasajeros.mp4`)
const pelicula_29= new Pelicula(`pelicula_29`, `Morbius`, `./assets/peliculas/Caraptula/Morbius.jpg`, `Ambientada en el universo de Spider Man, se centra en uno de sus villanos más icónicos, Morbius, un doctor que tras sufrir una enfermedad en la sangre y fallar al intentar curarse, se convirtió en un vampiro.`, `1 de abril de 2022`, `2022`, `Daniel Espinosa`, `104 minutos`, `./assets/peliculas/Video/Morbius.mp4`)
const pelicula_30= new Pelicula(`pelicula_30`, `Doctor Strange en el Multiverso de la Locura`, `./assets/peliculas/Caraptula/Doctor_Strange_2.jpg`, `El Dr. Stephen Strange abre un portal al multiverso al utilizar un hechizo prohibido. Ahora, su equipo debe enfrentarse a una amenaza que podría destruirlo todo.`, `6 de mayo de 2022`, `2022`, `Sam Raimi`, `126 minutos`, `./assets/peliculas/Video/Doctor_Strange_2.mp4`)
const pelicula_31= new Pelicula(`pelicula_31`, `El Proyecto Adam`, `./assets/peliculas/Caraptula/El_proyecto_Adam.jpg`, `Adam Reed, un viajero del tiempo y piloto de combate, aterriza en el año 2022. Allí, se encuentra con su yo de doce años y, junto a él, tratará de salvar el futuro.`, ` 28 de febrero de 2022`, `2022`, `Shawn Levy`, `106 minutos`, `./assets/peliculas/Video/El_proyecto_Adam.mp4`)
const pelicula_32= new Pelicula(`pelicula_32`, `Jurassic World: Dominion`, `./assets/peliculas/Caraptula/Jurassic_World_Dominion.jpg`, `La isla Nublar y su parque han sido destruidos, pero el problema no se terminó. Con los dinosaurios dispersos por todo el mundo, la convivencia entre el presente y el pasado alcanza un nuevo nivel de tensión.`, `10 de junio de 2022`, `2022`, `Colin Trevorrow`, `147 minutos`, `./assets/peliculas/Video/Jurassic_World_Dominion.mp4`)
//objeto a partir del cual se consultara todas las peliculas previamente instanciadas
export const lista_peliculas={
    Peliculas: [[pelicula_1, pelicula_2, pelicula_3, pelicula_4, pelicula_5, pelicula_6, pelicula_7, pelicula_8, pelicula_9, pelicula_10, pelicula_11, pelicula_12, pelicula_13, pelicula_14, pelicula_15, pelicula_16], [pelicula_17, pelicula_18, pelicula_19, pelicula_20, pelicula_21, pelicula_22, pelicula_23, pelicula_24, pelicula_25, pelicula_26, pelicula_27, pelicula_28, pelicula_29, pelicula_30, pelicula_31, pelicula_32]],
    Generos: {
        Anime: [[pelicula_1,pelicula_2,pelicula_3,pelicula_4,pelicula_5,pelicula_6,pelicula_7,pelicula_8]],
        Acción: [[pelicula_1,pelicula_3,pelicula_5,pelicula_8,pelicula_11,pelicula_13,pelicula_14,pelicula_16,pelicula_17,pelicula_18,pelicula_19,pelicula_20,pelicula_21,pelicula_22,pelicula_23,pelicula_24],[pelicula_25,pelicula_26,pelicula_29,pelicula_30,pelicula_31,pelicula_32]],
        Romance: [[pelicula_2,pelicula_4,pelicula_6,pelicula_13,pelicula_24,pelicula_27,pelicula_28]],
        Aventura: [[pelicula_1,pelicula_5,pelicula_7,pelicula_8,pelicula_13,pelicula_14,pelicula_15,pelicula_16,pelicula_17,pelicula_18,pelicula_19,pelicula_20,pelicula_23,pelicula_24,pelicula_25,pelicula_26],[pelicula_27,pelicula_29,pelicula_31,pelicula_32]],
        Marvel: [[pelicula_16,pelicula_25,pelicula_26,pelicula_29,pelicula_30]],
        DC: [[pelicula_17,pelicula_18,pelicula_21,pelicula_22,pelicula_23,pelicula_24]],
        Terror: [[pelicula_9,pelicula_10,pelicula_11,pelicula_12,pelicula_30]],
        Comedia: [[pelicula_1,pelicula_14,pelicula_15,pelicula_21,pelicula_27]],
        Drama:[[pelicula_13,pelicula_19,pelicula_24,pelicula_27,pelicula_28]],
        Ciencia_Fision:[[pelicula_16,pelicula_17,pelicula_18,pelicula_19,pelicula_21,pelicula_22,pelicula_23,pelicula_24,pelicula_25,pelicula_26,pelicula_28,pelicula_29,pelicula_30,pelicula_31,pelicula_32]],
        Fantasia:[[pelicula_1,pelicula_2,pelicula_3,pelicula_4,pelicula_5,pelicula_6,pelicula_7,pelicula_8,pelicula_15,pelicula_20,pelicula_21]]
    },
    Estrenos:[pelicula_29,pelicula_30,pelicula_18,pelicula_31,pelicula_32],
    Vistas:[pelicula_1,pelicula_17,pelicula_25, pelicula_30, pelicula_32 ]
}
